package com.example.messagingstompwebsocket.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.messagingstompwebsocket.model.Message;
import com.example.messagingstompwebsocket.repositories.MessageRepository;
import com.example.messagingstompwebsocket.service.PushNotificationService;


@Controller

public class MessageController {
	private Logger logger = LoggerFactory.getLogger(MessageController.class);
	@Autowired // This means to get the bean called userRepository
	   // Which is auto-generated by Spring, we will use it to handle the data
	private MessageRepository messageRepository;
	
	@PostMapping(path="/postmessage") // Map ONLY POST Requests
	public @ResponseBody String addNewMessage (@RequestBody Message message) {
		messageRepository.save(message);
		logger.info(message.getMessage());
		return "Saved";
		
	}
	
}
